export const FETCHING_EQUIPMENT_STARTED = 'FETCHING_EQUIPMENT_STARTED';
export const FETCHING_EQUIPMENT_COMPLETED = 'FETCHING_EQUIPMENT_COMPLETED';
export const FETCHING_EQUIPMENT_FAILED = 'FETCHING_EQUIPMENT_FAILED';

export const LOAN_EQUIPMENT_STARTED = 'LOAN_EQUIPMENT_STARTED';
export const LOAN_EQUIPMENT_COMPLETED= 'LOAN_EQUIPMENT_COMPLETED';
export const LOAN_EQUIPMENT_FAILED = 'LOAN_EQUIPMENT_FAILED';

export const RETURN_EQUIPMENT_STARTED = 'RETURN_EQUIPMENT_STARTED';
export const RETURN_EQUIPMENT_COMPLETED = 'RETURN_EQUIPMENT_COMPLETED';
export const RETURN_EQUIPMENT_FAILED = 'RETURN_EQUIPMENT_FAILED';

export const FETCHING_LOAN_EQUIPMENT_COLLECTION_STARTED = 'FETCHING_LOAN_EQUIPMENT_COLLECTION_STARTED';
export const FETCHING_LOAN_EQUIPMENT_COLLECTION_COMPLETED = 'FETCHING_LOAN_EQUIPMENT_COLLECTION_COMPLETED';
export const FECTHING_LOAN_EQUIPMENT_COLLECTION_FAILED = 'FECTHING_LOAN_EQUIPMENT_COLLECTION_FAILED';