export const RETRIEVING_STARTED = 'RETRIEVING_STARTED';
export const RETRIEVING_COMPLETED = 'RETRIEVING_COMPLETED';
export const RETRIEVING_FAILED = 'RETRIEVING_FAILED';

export const BUYING_STARTED = 'BUYING_STARTED';
export const BUYING_COMPLETED = 'BUYING_COMPLETED';
export const BUYING_FAILED = 'BUYING_FAILED';
