export const VIEW_BOOK_COLLECTION_STARTED = 'VIEW_BOOK_COLLECTION_STARTED';
export const VIEW_BOOK_COLLECTION_COMPLETED = 'VIEW_BOOK_COLLECTION_COMPLETED';
export const VIEW_BOOK_COLLECTION_FAILED = 'VIEW_BOOK_COLLECTION_FAILED';

export const BUTTON_PRESSED = 'BUTTON_PRESSED';
export const BUTTON_UNPRESSED = 'BUTTON_UNPRESSED';

export const PDF_FETCHING_STARTED = 'PDF_FETCHING_STARTED';
export const PDF_FETCHING_COMPLETED = 'PDF_FETCHING_COMPLETED';
export const PDF_FETCHING_FAILED = 'PDF_FETCHING_FAILED';
