export const RETRIEVING_STARTED = 'RETRIEVING_STARTED';
export const RETRIEVING_COMPLETED = 'RETRIEVING_COMPLETED';
export const RETRIEVING_FAILED = 'RETRIEVING_FAILED';

export const ADDING_TO_CART = 'RETRIEVING_STARTED';
export const REMOVING_FROM_CART = 'RETRIEVING_COMPLETED';
