export const FETCHING_BOOKS_STARTED = 'FETCHING_BOOKS_STARTED';
export const FETCHING_BOOKS_COMPLETED = 'FETCHING_BOOKS_COMPLETED';
export const FETCHING_BOOKS_FAILED = 'FETCHING_BOOKS_FAILED';

export const LOAN_A_BOOK_STARTED = 'LOAN_A_BOOK_STARTED';
export const LOAN_A_BOOK_COMPLETED= 'LOAN_A_BOOK_COMPLETED';
export const LOAN_A_BOOK_FAILED = 'LOAN_A_BOOK_FAILED';

export const RETURN_A_BOOK_STARTED = 'RETURN_A_BOOK_STARTED';
export const RETURN_A_BOOK_COMPLETED = 'RETURN_A_BOOK_COMPLETED';
export const RETURN_A_BOOK_FAILED = 'RETURN_A_BOOK_FAILED';