export const LOGIN_STARTED = 'LOGIN_STARTED';
export const LOGIN_COMPLETED = 'LOGIN_COMPLETED';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const AUTHENTICATION_IDENTITY_CLEARED = 'AUTHENTICATION_IDENTITY_CLEARED';
export const TOKEN_REFRESH_STARTED = 'TOKEN_REFRESH_STARTED';
export const TOKEN_REFRESH_COMPLETED = 'TOKEN_REFRESH_COMPLETED';
export const TOKEN_REFRESH_FAILED = 'TOKEN_REFRESH_FAILED';

