export const VIEW_MAGAZINE_COLLECTION_STARTED = 'VIEW_MAGAZINE_COLLECTION_STARTED';
export const VIEW_MAGAZINE_COLLECTION_COMPLETED = 'VIEW_MAGAZINE_COLLECTION_COMPLETED';
export const VIEW_MAGAZINE_COLLECTION_FAILED = 'VIEW_MAGAZINE_COLLECTION_FAILED';

export const MAGAZINE_COLLECTION_BUTTON_PRESSED = 'MAGAZINE_COLLECTION_BUTTON_PRESSED';
export const MAGAZINE_COLLECTION_BUTTON_UNPRESSED = 'MAGAZINE_COLLECTION_BUTTON_UNPRESSED';

export const MAGAZINE_PDF_FETCHING_STARTED = 'MAGAZINE_PDF_FETCHING_STARTED';
export const MAGAZINE_PDF_FETCHING_COMPLETED = 'MAGAZINE_PDF_FETCHING_COMPLETED';
export const MAGAZINE_PDF_FETCHING_FAILED = 'MAGAZINE_PDF_FETCHING_FAILED';