export const MAGAZINE_RETRIEVING_STARTED =   'MAGAZINE_RETRIEVING_STARTED';
export const MAGAZINE_RETRIEVING_COMPLETED = 'MAGAZINE_RETRIEVING_COMPLETED';
export const MAGAZINE_RETRIEVING_FAILED =    'MAGAZINE_RETRIEVING_FAILED';

export const MAGAZINE_BUYING_STARTED =   'MAGAZINE_BUYING_STARTED';
export const MAGAZINE_BUYING_COMPLETED = 'MAGAZINE_BUYING_COMPLETED';
export const MAGAZINE_BUYING_FAILED =    'MAGAZINE_BUYING_FAILED';