export const PAYMENT_OPTION_FETCHING_STARTED = 'PAYMENT_OPTION_FETCHING_STARTED';
export const PAYMENT_OPTION_FETCHING_COMPLETED = 'PAYMENT_OPTION_FETCHING_COMPLETED';
export const PAYMENT_OPTION_FETCHING_FAILED = 'PAYMENT_OPTION_FETCHING_FAILED';

export const ADD_FOUNDS_FETCHING_STARTED = 'ADD_FOUNDS_FETCHING_STARTED';
export const ADD_FOUNDS_FETCHING_COMPLETED = 'ADD_FOUNDS_FETCHING_COMPLETED';
export const ADD_FOUNDS_FETCHING_FAILED = 'ADD_FOUNDS_FETCHING_FAILED';

export const CHANGE_PAYMENT_OPTIONS_STARTED = 'CHANGE_PAYMENT_OPTIONS_STARTED';
export const CHANGE_PAYMENT_OPTIONS_COMPLETED = 'CHANGE_PAYMENT_OPTIONS_COMPLETED';
export const CHANGE_PAYMENT_OPTIONS_FAILED = 'CHANGE_PAYMENT_OPTIONS_FAILED';
