/**
 * Upload Profile Image SCF
 * Update Profile Data SCF
 * View book collection
 */
export const UPLOAD_PROFILE_PICTURE_STARTED = 'UPLOAD_PROFILE_PICTURE_STARTED';
export const UPLOAD_PROFILE_PICTURE_COMPLETED =
  'UPLOAD_PROFILE_PICTURE_COMPLETED';
export const UPLOAD_PROFILE_PICTURE_FAILED = 'UPLOAD_PROFILE_PICTURE_FAILED';

// export const UPDATE_PROFILE_DATA_STARTED = 'UPDATE_PROFILE_DATA_STARTED';
// export const UPDATE_PROFILE_DATA_COMPLETED = 'UPDATE_PROFILE_DATA_COMPLETED';
// export const UPDATE_PROFILE_DATA_FAILED = 'UPDATE_PROFILE_DATA_FAILED';

export const VIEW_BOOK_COLLECTION_STARTED = 'VIEW_BOOK_COLLECTION_STARTED';
export const VIEW_BOOK_COLLECTION_COMPLETED = 'VIEW_BOOK_COLLECTION_COMPLETED';
export const VIEW_BOOK_COLLECTION_FAILED = 'VIEW_BOOK_COLLECTION_FAILED';

export const CHANGE_DESCRIPTION_STARTED = 'CHANGE_DESCRIPTION_STARTED';
export const CHANGE_DESCRIPTION_COMPLETED = 'CHANGE_DESCRIPTION_COMPLETED';
export const CHANGE_DESCRIPTION_FAILED = 'CHANGE_DESCRIPTION_FAILED';

export const RETRIEVE_PROFILE_STARTED = 'RETRIEVE_PROFILE_STARTED';
export const RETRIEVE_PROFILE_COMPLETED = 'RETRIEVE_PROFILE_COMPLETED';
export const RETRIEVE_PROFILE_FAILED = 'RETRIEVE_PROFILE_FAILED';
